# Generated by Django 5.2.12 on 2026-04-15 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_renovationtype'),
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('operation_type', models.CharField(choices=[('rent', 'Аренда'), ('buy', 'Покупка')], max_length=20, verbose_name='Тип операции')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, null=True, verbose_name='Слаг')),
                ('price_usd', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Цена в USD')),
                ('price_uzs', models.DecimalField(blank=True, decimal_places=3, help_text='Цена будет высчитываться от price_usd после сохранения объявления', max_digits=12, null=True, verbose_name='Цена в UZS')),
                ('description', models.TextField(verbose_name='Описание')),
                ('complex_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название жилого комплекса')),
                ('special_conditions', models.TextField(blank=True, null=True, verbose_name='Специальные условия')),
                ('total_area', models.FloatField(verbose_name='Общая площадь')),
                ('living_space', models.FloatField(verbose_name='Жилая площадь')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('number_of_floors', models.IntegerField(blank=True, null=True, verbose_name='Этажность')),
                ('ceiling_height', models.FloatField(default=0, verbose_name='Высота потолков')),
                ('year_of_construction', models.IntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('rooms_quantity', models.IntegerField(default=0, verbose_name='Количество комнат')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='advertisements/previews/%Y/%m/%d/', verbose_name='Заставка')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Прошло модерацию?')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='categories.category', verbose_name='Категория')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='districts.district', verbose_name='Район')),
                ('renovation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.renovationtype', verbose_name='Тип ремонта')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementCharacterstic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('key', models.CharField(max_length=150, verbose_name='Название характеристики')),
                ('value', models.CharField(max_length=150, verbose_name='Значение характеристики')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='advertisements.advertisement')),
            ],
            options={
                'verbose_name': 'Характеристика объявления',
                'verbose_name_plural': 'Характеристики объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to='advertisements/images/%Y/%m/%d/', verbose_name='Фотография')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisements.advertisement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Фотография объявления',
                'verbose_name_plural': 'Фотографии объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
