# Generated by Django 5.2.12 on 2026-04-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_price_uzs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price_uzs',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Цена будет высчитываться от price_usd по курса: '12015.96' после сохранения объявления", max_digits=12, null=True, verbose_name='Цена в UZS'),
        ),
    ]
