# Generated by Django 5.2.12 on 2026-04-14 05:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_consultingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('deadlines', models.CharField(max_length=20, verbose_name='Сроки')),
                ('format', models.CharField(max_length=60, verbose_name='Формат')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInclude',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_includes', to='main.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Пункт услуги',
                'verbose_name_plural': 'Пункты услуги',
                'ordering': ['-created_at'],
            },
        ),
    ]
