# Generated by Django 5.2.12 on 2026-04-14 05:51

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service_serviceinclude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('video', models.FileField(upload_to='portfolio/videos/%Y/%m/%d', verbose_name='Видео')),
                ('jobs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('photos_job', 'Фотографии, подчеркивающие свет и пространство.'), ('video_job', 'Съемка и монтаж видео'), ('ai_job', 'AI контент'), ('result_job', 'Реализация от концепции до результата')], max_length=100, verbose_name='Было сделано'), blank=True, default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to='portfolio/images/%Y/%m/%d', verbose_name='Фото')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.portfolio', verbose_name='Проект в портфолио')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
