# Generated by Django 5.2.12 on 2026-04-14 06:12

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_portfolio_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='jobs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200, verbose_name=models.CharField(choices=[('photos_job', 'Фотографии, подчеркивающие свет и пространство.'), ('video_job', 'Съемка и монтаж видео'), ('AI контент', 'result_job'), ('ai_job', 'Реализация от концепции до результата')], max_length=100)),
        ),
    ]
