# Generated by Django 5.2.12 on 2026-04-14 06:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_portfolio_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='jobs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('photos_job', 'Фотографии, подчеркивающие свет и пространство.'), ('video_job', 'Съемка и монтаж видео'), ('AI контент', 'result_job'), ('ai_job', 'Реализация от концепции до результата')]), size=None, verbose_name='Было выполнено'),
        ),
    ]
