# Generated by Django 5.2.12 on 2026-04-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_portfolio_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='jobs',
        ),
    ]
