# Generated by Django 5.2.12 on 2026-04-14 09:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_portfolio_options_portfoliojob'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Заявка на обратную связь',
                'verbose_name_plural': 'Заявки на обратную связь',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='portfoliojob',
            name='job',
            field=models.CharField(choices=[('photos_job', 'Фотографии, подчеркивающие свет и пространство.'), ('video_job', 'Съемка и монтаж видео'), ('result_job', 'AI контент'), ('ai_job', 'Реализация от концепции до результата')], max_length=70, verbose_name='Выполненная работа'),
        ),
    ]
